DROP TABLE IF EXISTS TB_HEROS;
CREATE TABLE TB_HEROS (
  ID TEXT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NOME TEXT NOT NULL,
  PODER TEXT NOT NULL
)

--CREATE
INSERT INTO TB_HEROS (NOME, PODER)
VALUES
  ('Flash', 'Velocidade'),
  ('Aquaman', 'Falar com os animais'),
  ('Batman', 'Dinheiro')

--READ
SELECT * FROM TB_HEROS;
SELECT * FROM TB_HEROS WHERE NOME='FLASH';

--UPDATE
UPDATE TB_HEROS
SET NOME = 'Goku', PODER = 'Nub'
WHERE ID = 1;

--DELETE
DELETE FROM TB_HEROS WHERE ID = 2;
